version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "tests"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "docs"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "benchmark"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "scripts"
    schedule:
      interval: "daily"
