site_name: apischema
repo_name: wyfo/apischema
repo_url: https://github.com/wyfo/apischema

theme:
  name: material
  palette:
    scheme: preference
    primary: green
    accent: indigo

nav:
- index.md
- data_model.md
- de_serialization.md
- json_schema.md
- validation.md
- Conversions: conversions.md
- GraphQL:
  - Overview: graphql/overview.md
  - graphql/data_model_and_resolvers.md
  - graphql/schema.md
  - graphql/relay.md
- Examples:
  - OpenRPC: examples/open_rpc.md
  - examples/sqlalchemy_support.md
  - examples/pydantic_support.md
  - examples/attrs_support.md
  - examples/subclass_union.md
  - examples/subclass_tagged_union.md
  - examples/recoverable_fields.md
  - examples/inherited_deserializer.md
- benchmark.md
- difference_with_pydantic.md
- Releases: https://github.com/wyfo/apischema/releases


markdown_extensions:
- markdown.extensions.codehilite:
    guess_lang: false
- markdown_include.include:
    base_path: examples
- toc:
    permalink: True
#    toc_depth: 3
- admonition
- codehilite
- extra
- attr_list

plugins:
- search
- exclude:
    glob:
    - requirements.txt

extra:
  version:
    provider: mike
